name: Fetch Project Data and Create PR

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

      - name: Fetch data and convert to YAML
        run: |
          # Install yq for JSON to YAML conversion
          sudo snap install yq
          
          # Run the API call and process output
          curl -H "Authorization: Bearer ${{ env.API_TOKEN }}" \
            "https://api-gw.platform.linuxfoundation.org/project-service/v1/projects/a0941000002wBz4AAE" | \
            jq '.Projects[] | select(.ProjectType == "Project" and (.Category == "Graduated" or .Category == "Sandbox" or .Category == "Incubating")) | {Name: .Name, RepositoryURL: .RepositoryURL, Category: .Category}' | \
            yq -P > projects.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update projects data"
          title: "Automated project data update"
          body: "This PR updates the projects data from PCC API"
          branch: "auto-project-update"
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}
