name: Fetch Project Data and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo snap install yq

      - name: Fetch and process data
        id: process
        run: |
          # Fetch data and process into YAML
          curl -H "Authorization: Bearer ${{ env.API_TOKEN }}" \
            "https://api-gw.platform.linuxfoundation.org/project-service/v1/projects/a0941000002wBz4AAE" | \
            jq '[.Projects[] | select(.ProjectType == "Project" and (.Category == "Graduated" or .Category == "Sandbox" or .Category == "Incubating")) | {Name: .Name, RepositoryURL: .RepositoryURL, Category: .Category}]' | \
            yq -P > projects.yaml
          # Fail if the file is empty or invalid
          if [ ! -s projects.yaml ]; then
            echo "Error: projects.yaml is empty or not created"
            exit 1
          fi

      - name: Debug output
        if: always()
        run: |
          echo "YAML output:"
          if [ -f projects.yaml ]; then
            cat projects.yaml
            echo "Total projects: $(yq eval '. | length' projects.yaml)"
          else
            echo "No YAML file generated"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update projects data"
          title: "Automated project data update"
          body: "This PR updates the projects data from the Linux Foundation API"
          branch: "auto-project-update"
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}